name: '48'
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.4.13=h06a4308_1
  - cairo=1.14.12=h8948797_3
  - certifi=2020.12.5=py37h06a4308_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - glib=2.66.1=h92f7085_0
  - graphite2=1.3.14=h23475e2_0
  - harfbuzz=2.4.0=hca77d97_1
  - icu=58.2=he6710b0_3
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=hb55368b_3
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pango=1.45.3=hd140c19_0
  - pcre=8.44=he6710b0_0
  - pip=20.3.3=py37h06a4308_0
  - pixman=0.40.0=h7b6447c_0
  - pkg-config=0.29.2=h1bed415_8
  - python=3.7.9=h7579374_0
  - readline=8.0=h7b6447c_0
  - setuptools=51.0.0=py37h06a4308_2
  - sphinx_rtd_theme=0.4.3=py_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - alabaster==0.7.12
    - babel==2.9.0
    - beautifulsoup4==4.9.3
    - chardet==4.0.0
    - cython==0.29.21
    - docutils==0.16
    - idna==2.10
    - imagesize==1.2.0
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - packaging==20.8
    - pygments==2.7.3
    - pyparsing==2.4.7
    - pytz==2020.5
    - requests==2.25.1
    - snowballstemmer==2.0.0
    - soupsieve==2.1
    - sphinx==3.4.1
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - sphinxext-opengraph==0.3.1
    - urllib3==1.26.2
